/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type QuemSou = {
  _id: string;
  _type: "quemSou";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  foto?: ImagemComAlt;
  historia?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImagemComAlt)
  >;
  credenciais?: Array<string>;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  titulo?: string;
  descricao?: string;
  imagem?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  naoIndexar?: boolean;
};

export type ImagemComAlt = {
  _type: "imagemComAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  legenda?: string;
};

export type Configuracao = {
  _id: string;
  _type: "configuracao";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  whatsapp?: string;
  email?: string;
  instagram?: string;
  heroTitulo?: string;
  heroSubtitulo?: string;
  heroImagem?: ImagemComAlt;
  peregrinosGuiados?: number;
  saidasRealizadas?: number;
  anoInicio?: number;
};

export type Lead = {
  _id: string;
  _type: "lead";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  whatsapp?: string;
  email?: string;
  origem?: string;
  saidaInteresse?: string;
  mensagem?: string;
  consentimento?: boolean;
  recebidoEm?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Material = {
  _id: string;
  _type: "material";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  promessa?: string;
  topicos?: Array<string>;
  capa?: ImagemComAlt;
  arquivo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  ativo?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pergunta?: string;
  resposta?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  categoria?: "decisao" | "fisico" | "equipamento" | "caminho" | "valores";
  ordem?: number;
  naHome?: boolean;
};

export type SaidaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "saida";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria?: "preparacao" | "espiritualidade" | "roteiros" | "relatos";
  resumo?: string;
  capa?: ImagemComAlt;
  publicadoEm?: string;
  corpo?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImagemComAlt)
    | {
        texto?: string;
        _type: "destaque";
        _key: string;
      }
  >;
  saidasRelacionadas?: Array<
    {
      _key: string;
    } & SaidaReference
  >;
  seo?: Seo;
};

export type Depoimento = {
  _id: string;
  _type: "depoimento";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  cidade?: string;
  saida?: SaidaReference;
  texto?: string;
  foto?: ImagemComAlt;
  videoUrl?: string;
  publicado?: boolean;
  destaque?: boolean;
};

export type RamalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "ramal";
};

export type Saida = {
  _id: string;
  _type: "saida";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  ramal?: RamalReference;
  dataInicio?: string;
  dataFim?: string;
  cidadeSaida?: string;
  resumo?: string;
  distanciaKm?: number;
  nivel?: "leve" | "moderado" | "exigente";
  roteiro?: Array<
    {
      _key: string;
    } & DiaRoteiro
  >;
  vagasTotal?: number;
  vagasDisponiveis?: number;
  valor?: string;
  incluso?: Array<string>;
  naoIncluso?: Array<string>;
  destaque?: boolean;
  imagemCapa?: ImagemComAlt;
  galeria?: Array<
    {
      _key: string;
    } & ImagemComAlt
  >;
  slugGrupo?: Slug;
  orientacoesGrupo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type Ramal = {
  _id: string;
  _type: "ramal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  slug?: Slug;
  cidadeInicio?: string;
  km?: number;
  diasSugeridos?: number;
  dificuldade?: "leve" | "moderado" | "exigente";
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  imagem?: ImagemComAlt;
  seo?: Seo;
};

export type DiaRoteiro = {
  _type: "diaRoteiro";
  dia?: number;
  trecho?: string;
  km?: number;
  altimetria?: number;
  pousada?: string;
  descricao?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | QuemSou
  | SanityImageAssetReference
  | Seo
  | ImagemComAlt
  | Configuracao
  | Lead
  | SanityFileAssetReference
  | Material
  | Slug
  | Faq
  | SaidaReference
  | Post
  | Depoimento
  | RamalReference
  | Saida
  | Ramal
  | DiaRoteiro
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src\sanity\queries.ts
// Variable: IMAGEM
// Query: {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}
export type IMAGEM_RESULT = never;

// Source: src\sanity\queries.ts
// Variable: SEO
// Query: seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }}
export type SEO_RESULT = never;

// Source: src\sanity\queries.ts
// Variable: CARTAO_SAIDA
// Query: {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type CARTAO_SAIDA_RESULT = {
  _id: never;
  titulo: never;
  slug: never;
  dataInicio: never;
  dataFim: never;
  cidadeSaida: never;
  resumo: never;
  distanciaKm: never;
  nivel: never;
  vagasTotal: never;
  vagasDisponiveis: never;
  valor: never;
  destaque: never;
  imagemCapa: never;
  ramal: never;
};

// Source: src\sanity\queries.ts
// Variable: PROXIMAS_SAIDAS
// Query: *[_type == "saida" && dataFim >= now()]  | order(dataInicio asc) {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type PROXIMAS_SAIDAS_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  resumo: string | null;
  distanciaKm: number | null;
  nivel: "exigente" | "leve" | "moderado" | null;
  vagasTotal: number | null;
  vagasDisponiveis: number | null;
  valor: string | null;
  destaque: boolean | null;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
  } | null;
}>;

// Source: src\sanity\queries.ts
// Variable: SAIDAS_HOME
// Query: *[_type == "saida" && dataFim >= now()]  | order(destaque desc, dataInicio asc)[0...$limite] {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type SAIDAS_HOME_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  resumo: string | null;
  distanciaKm: number | null;
  nivel: "exigente" | "leve" | "moderado" | null;
  vagasTotal: number | null;
  vagasDisponiveis: number | null;
  valor: string | null;
  destaque: boolean | null;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
  } | null;
}>;

// Source: src\sanity\queries.ts
// Variable: SAIDAS_REALIZADAS
// Query: *[_type == "saida" && dataFim < now()]  | order(dataInicio desc) {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type SAIDAS_REALIZADAS_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  resumo: string | null;
  distanciaKm: number | null;
  nivel: "exigente" | "leve" | "moderado" | null;
  vagasTotal: number | null;
  vagasDisponiveis: number | null;
  valor: string | null;
  destaque: boolean | null;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
  } | null;
}>;

// Source: src\sanity\queries.ts
// Variable: SAIDA_POR_SLUG
// Query: *[_type == "saida" && slug.current == $slug][0]{    ...,    "slug": slug.current,    imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    galeria[] {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    ramal->{ nome, "slug": slug.current, km, dificuldade, cidadeInicio },    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },    incluso,    naoIncluso,    seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }},    "depoimentos": *[_type == "depoimento" && publicado == true                     && references(^._id)] | order(_createdAt desc){      _id, nome, cidade, texto, videoUrl, foto {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}    },    "perguntas": *[_type == "faq" && categoria in ["decisao", "valores"]]                 | order(ordem asc)[0...6]{ _id, pergunta, resposta }  }
export type SAIDA_POR_SLUG_RESULT = {
  _id: string;
  _type: "saida";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug: string | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
    dificuldade: "exigente" | "leve" | "moderado" | null;
    cidadeInicio: string | null;
  } | null;
  dataInicio?: string;
  dataFim?: string;
  cidadeSaida?: string;
  resumo?: string;
  distanciaKm?: number;
  nivel?: "exigente" | "leve" | "moderado";
  roteiro: Array<{
    dia: number | null;
    trecho: string | null;
    km: number | null;
    altimetria: number | null;
    pousada: string | null;
    descricao: string | null;
  }> | null;
  vagasTotal?: number;
  vagasDisponiveis?: number;
  valor?: string;
  incluso: Array<string> | null;
  naoIncluso: Array<string> | null;
  destaque?: boolean;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  galeria: Array<{
    _key: string;
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  }> | null;
  slugGrupo?: Slug;
  orientacoesGrupo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo: {
    titulo: string | null;
    descricao: string | null;
    naoIndexar: boolean | null;
    imagem: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      lqip: string | null;
    } | null;
  } | null;
  depoimentos: Array<{
    _id: string;
    nome: string | null;
    cidade: string | null;
    texto: string | null;
    videoUrl: string | null;
    foto: {
      _type: "imagemComAlt";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      legenda?: string;
      lqip: string | null;
      dimensoes: SanityImageDimensions | null;
    } | null;
  }>;
  perguntas: Array<{
    _id: string;
    pergunta: string | null;
    resposta: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }>;
} | null;

// Source: src\sanity\queries.ts
// Variable: SLUGS_SAIDA
// Query: *[_type == "saida" && defined(slug.current)][]{ "slug": slug.current }
export type SLUGS_SAIDA_RESULT = Array<{
  slug: string | null;
}>;

// Source: src\sanity\queries.ts
// Variable: GRUPO_POR_SLUG
// Query: *[_type == "saida" && slugGrupo.current == $slug][0]{    titulo, dataInicio, dataFim, cidadeSaida, distanciaKm,    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },    orientacoesGrupo,    incluso, naoIncluso,    ramal->{ nome, km }  }
export type GRUPO_POR_SLUG_RESULT = {
  titulo: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  distanciaKm: number | null;
  roteiro: Array<{
    dia: number | null;
    trecho: string | null;
    km: number | null;
    altimetria: number | null;
    pousada: string | null;
    descricao: string | null;
  }> | null;
  orientacoesGrupo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  incluso: Array<string> | null;
  naoIncluso: Array<string> | null;
  ramal: {
    nome: string | null;
    km: number | null;
  } | null;
} | null;

// Source: src\sanity\queries.ts
// Variable: CONFIGURACAO
// Query: *[_type == "configuracao"][0]{    whatsapp, email, instagram,    heroTitulo, heroSubtitulo,    heroImagem {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    peregrinosGuiados, saidasRealizadas, anoInicio  }
export type CONFIGURACAO_RESULT = {
  whatsapp: string | null;
  email: string | null;
  instagram: string | null;
  heroTitulo: string | null;
  heroSubtitulo: string | null;
  heroImagem: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  peregrinosGuiados: number | null;
  saidasRealizadas: number | null;
  anoInicio: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}': IMAGEM_RESULT;
    'seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n}': SEO_RESULT;
    '{\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}': CARTAO_SAIDA_RESULT;
    '\n  *[_type == "saida" && dataFim >= now()]\n  | order(dataInicio asc) {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}\n': PROXIMAS_SAIDAS_RESULT;
    '\n  *[_type == "saida" && dataFim >= now()]\n  | order(destaque desc, dataInicio asc)[0...$limite] {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}\n': SAIDAS_HOME_RESULT;
    '\n  *[_type == "saida" && dataFim < now()]\n  | order(dataInicio desc) {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}\n': SAIDAS_REALIZADAS_RESULT;
    '\n  *[_type == "saida" && slug.current == $slug][0]{\n    ...,\n    "slug": slug.current,\n    imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    galeria[] {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    ramal->{ nome, "slug": slug.current, km, dificuldade, cidadeInicio },\n    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },\n    incluso,\n    naoIncluso,\n    seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n},\n    "depoimentos": *[_type == "depoimento" && publicado == true\n                     && references(^._id)] | order(_createdAt desc){\n      _id, nome, cidade, texto, videoUrl, foto {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n    },\n    "perguntas": *[_type == "faq" && categoria in ["decisao", "valores"]]\n                 | order(ordem asc)[0...6]{ _id, pergunta, resposta }\n  }\n': SAIDA_POR_SLUG_RESULT;
    '\n  *[_type == "saida" && defined(slug.current)][]{ "slug": slug.current }\n': SLUGS_SAIDA_RESULT;
    '\n  *[_type == "saida" && slugGrupo.current == $slug][0]{\n    titulo, dataInicio, dataFim, cidadeSaida, distanciaKm,\n    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },\n    orientacoesGrupo,\n    incluso, naoIncluso,\n    ramal->{ nome, km }\n  }\n': GRUPO_POR_SLUG_RESULT;
    '\n  *[_type == "configuracao"][0]{\n    whatsapp, email, instagram,\n    heroTitulo, heroSubtitulo,\n    heroImagem {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    peregrinosGuiados, saidasRealizadas, anoInicio\n  }\n': CONFIGURACAO_RESULT;
  }
}
