/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type QuemSou = {
  _id: string;
  _type: "quemSou";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  foto?: ImagemComAlt;
  historia?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImagemComAlt)
  >;
  credenciais?: Array<string>;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  titulo?: string;
  descricao?: string;
  imagem?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  naoIndexar?: boolean;
};

export type ImagemComAlt = {
  _type: "imagemComAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  legenda?: string;
};

export type Configuracao = {
  _id: string;
  _type: "configuracao";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  whatsapp?: string;
  email?: string;
  instagram?: string;
  heroTitulo?: string;
  heroSubtitulo?: string;
  heroImagem?: ImagemComAlt;
  heroCitacao?: string;
  peregrinosGuiados?: number;
  saidasRealizadas?: number;
  anoInicio?: number;
};

export type Lead = {
  _id: string;
  _type: "lead";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  whatsapp?: string;
  email?: string;
  origem?: string;
  saidaInteresse?: string;
  mensagem?: string;
  consentimento?: boolean;
  recebidoEm?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Material = {
  _id: string;
  _type: "material";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  promessa?: string;
  topicos?: Array<string>;
  capa?: ImagemComAlt;
  arquivo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  ativo?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pergunta?: string;
  resposta?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  categoria?: "decisao" | "fisico" | "equipamento" | "caminho" | "valores";
  ordem?: number;
  naHome?: boolean;
};

export type SaidaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "saida";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria?: "preparacao" | "espiritualidade" | "roteiros" | "relatos";
  resumo?: string;
  capa?: ImagemComAlt;
  publicadoEm?: string;
  corpo?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImagemComAlt)
    | {
        texto?: string;
        _type: "destaque";
        _key: string;
      }
  >;
  saidasRelacionadas?: Array<
    {
      _key: string;
    } & SaidaReference
  >;
  seo?: Seo;
};

export type Depoimento = {
  _id: string;
  _type: "depoimento";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  cidade?: string;
  saida?: SaidaReference;
  texto?: string;
  foto?: ImagemComAlt;
  videoUrl?: string;
  publicado?: boolean;
  destaque?: boolean;
};

export type RamalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "ramal";
};

export type Saida = {
  _id: string;
  _type: "saida";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  ramal?: RamalReference;
  dataInicio?: string;
  dataFim?: string;
  cidadeSaida?: string;
  resumo?: string;
  distanciaKm?: number;
  nivel?: "leve" | "moderado" | "exigente";
  roteiro?: Array<
    {
      _key: string;
    } & DiaRoteiro
  >;
  vagasTotal?: number;
  vagasDisponiveis?: number;
  valor?: string;
  incluso?: Array<string>;
  naoIncluso?: Array<string>;
  destaque?: boolean;
  imagemCapa?: ImagemComAlt;
  galeria?: Array<
    {
      _key: string;
    } & ImagemComAlt
  >;
  slugGrupo?: Slug;
  orientacoesGrupo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type Ramal = {
  _id: string;
  _type: "ramal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  slug?: Slug;
  cidadeInicio?: string;
  km?: number;
  diasSugeridos?: number;
  dificuldade?: "leve" | "moderado" | "exigente";
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  imagem?: ImagemComAlt;
  seo?: Seo;
};

export type DiaRoteiro = {
  _type: "diaRoteiro";
  dia?: number;
  trecho?: string;
  km?: number;
  altimetria?: number;
  pousada?: string;
  descricao?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | QuemSou
  | SanityImageAssetReference
  | Seo
  | ImagemComAlt
  | Configuracao
  | Lead
  | SanityFileAssetReference
  | Material
  | Slug
  | Faq
  | SaidaReference
  | Post
  | Depoimento
  | RamalReference
  | Saida
  | Ramal
  | DiaRoteiro
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: IMAGEM
// Query: {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}
export type IMAGEM_RESULT = never;

// Source: src/sanity/queries.ts
// Variable: SEO
// Query: seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }}
export type SEO_RESULT = never;

// Source: src/sanity/queries.ts
// Variable: CARTAO_SAIDA
// Query: {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type CARTAO_SAIDA_RESULT = {
  _id: never;
  titulo: never;
  slug: never;
  dataInicio: never;
  dataFim: never;
  cidadeSaida: never;
  resumo: never;
  distanciaKm: never;
  nivel: never;
  vagasTotal: never;
  vagasDisponiveis: never;
  valor: never;
  destaque: never;
  imagemCapa: never;
  ramal: never;
};

// Source: src/sanity/queries.ts
// Variable: PROXIMAS_SAIDAS
// Query: *[_type == "saida" && dataFim >= now()]  | order(dataInicio asc) {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type PROXIMAS_SAIDAS_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  resumo: string | null;
  distanciaKm: number | null;
  nivel: "exigente" | "leve" | "moderado" | null;
  vagasTotal: number | null;
  vagasDisponiveis: number | null;
  valor: string | null;
  destaque: boolean | null;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: RODAPE_SAIDAS
// Query: *[_type == "saida" && dataFim >= now()]  | order(dataInicio asc)[0...3]{    titulo, "slug": slug.current, dataInicio  }
export type RODAPE_SAIDAS_RESULT = Array<{
  titulo: string | null;
  slug: string | null;
  dataInicio: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SAIDAS_HOME
// Query: *[_type == "saida" && dataFim >= now()]  | order(destaque desc, dataInicio asc)[0...$limite] {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type SAIDAS_HOME_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  resumo: string | null;
  distanciaKm: number | null;
  nivel: "exigente" | "leve" | "moderado" | null;
  vagasTotal: number | null;
  vagasDisponiveis: number | null;
  valor: string | null;
  destaque: boolean | null;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SAIDAS_REALIZADAS
// Query: *[_type == "saida" && dataFim < now()]  | order(dataInicio desc) {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}
export type SAIDAS_REALIZADAS_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  resumo: string | null;
  distanciaKm: number | null;
  nivel: "exigente" | "leve" | "moderado" | null;
  vagasTotal: number | null;
  vagasDisponiveis: number | null;
  valor: string | null;
  destaque: boolean | null;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SAIDA_POR_SLUG
// Query: *[_type == "saida" && slug.current == $slug][0]{    ...,    "slug": slug.current,    imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    galeria[] {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    ramal->{ nome, "slug": slug.current, km, dificuldade, cidadeInicio },    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },    incluso,    naoIncluso,    seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }},    "depoimentos": *[_type == "depoimento" && publicado == true                     && references(^._id)] | order(_createdAt desc){      _id, nome, cidade, texto, videoUrl, foto {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}    },    "perguntas": *[_type == "faq" && categoria in ["decisao", "valores"]]                 | order(ordem asc)[0...6]{ _id, pergunta, resposta }  }
export type SAIDA_POR_SLUG_RESULT = {
  _id: string;
  _type: "saida";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug: string | null;
  ramal: {
    nome: string | null;
    slug: string | null;
    km: number | null;
    dificuldade: "exigente" | "leve" | "moderado" | null;
    cidadeInicio: string | null;
  } | null;
  dataInicio?: string;
  dataFim?: string;
  cidadeSaida?: string;
  resumo?: string;
  distanciaKm?: number;
  nivel?: "exigente" | "leve" | "moderado";
  roteiro: Array<{
    dia: number | null;
    trecho: string | null;
    km: number | null;
    altimetria: number | null;
    pousada: string | null;
    descricao: string | null;
  }> | null;
  vagasTotal?: number;
  vagasDisponiveis?: number;
  valor?: string;
  incluso: Array<string> | null;
  naoIncluso: Array<string> | null;
  destaque?: boolean;
  imagemCapa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  galeria: Array<{
    _key: string;
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  }> | null;
  slugGrupo?: Slug;
  orientacoesGrupo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo: {
    titulo: string | null;
    descricao: string | null;
    naoIndexar: boolean | null;
    imagem: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      lqip: string | null;
    } | null;
  } | null;
  depoimentos: Array<{
    _id: string;
    nome: string | null;
    cidade: string | null;
    texto: string | null;
    videoUrl: string | null;
    foto: {
      _type: "imagemComAlt";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      legenda?: string;
      lqip: string | null;
      dimensoes: SanityImageDimensions | null;
    } | null;
  }>;
  perguntas: Array<{
    _id: string;
    pergunta: string | null;
    resposta: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }>;
} | null;

// Source: src/sanity/queries.ts
// Variable: SLUGS_SAIDA
// Query: *[_type == "saida" && defined(slug.current)][]{ "slug": slug.current }
export type SLUGS_SAIDA_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: GRUPO_POR_SLUG
// Query: *[_type == "saida" && slugGrupo.current == $slug][0]{    titulo, dataInicio, dataFim, cidadeSaida, distanciaKm,    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },    orientacoesGrupo,    incluso, naoIncluso,    ramal->{ nome, km }  }
export type GRUPO_POR_SLUG_RESULT = {
  titulo: string | null;
  dataInicio: string | null;
  dataFim: string | null;
  cidadeSaida: string | null;
  distanciaKm: number | null;
  roteiro: Array<{
    dia: number | null;
    trecho: string | null;
    km: number | null;
    altimetria: number | null;
    pousada: string | null;
    descricao: string | null;
  }> | null;
  orientacoesGrupo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  incluso: Array<string> | null;
  naoIncluso: Array<string> | null;
  ramal: {
    nome: string | null;
    km: number | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: CONFIGURACAO
// Query: *[_type == "configuracao"][0]{    whatsapp, email, instagram,    heroTitulo, heroSubtitulo, heroCitacao,    heroImagem {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    peregrinosGuiados, saidasRealizadas, anoInicio  }
export type CONFIGURACAO_RESULT = {
  whatsapp: string | null;
  email: string | null;
  instagram: string | null;
  heroTitulo: string | null;
  heroSubtitulo: string | null;
  heroCitacao: string | null;
  heroImagem: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  peregrinosGuiados: number | null;
  saidasRealizadas: number | null;
  anoInicio: number | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: QUEM_SOU
// Query: *[_type == "quemSou"][0]{    titulo, credenciais,    foto {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    historia[]{ ..., _type == "imagemComAlt" => {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions} },    seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }}  }
export type QUEM_SOU_RESULT = {
  titulo: string | null;
  credenciais: Array<string> | null;
  foto: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  historia: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "imagemComAlt";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | "";
        legenda?: string;
        lqip: string | null;
        dimensoes: SanityImageDimensions | null;
      }
  > | null;
  seo: {
    titulo: string | null;
    descricao: string | null;
    naoIndexar: boolean | null;
    imagem: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      lqip: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: DEPOIMENTOS_HOME
// Query: *[_type == "depoimento" && publicado == true]  | order(destaque desc, _createdAt desc)[0...8]{    _id, nome, cidade, texto,    foto {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    saida->{ dataInicio, ramal->{ nome } }  }
export type DEPOIMENTOS_HOME_RESULT = Array<{
  _id: string;
  nome: string | null;
  cidade: string | null;
  texto: string | null;
  foto: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  saida: {
    dataInicio: string | null;
    ramal: {
      nome: string | null;
    } | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FAQ_HOME
// Query: *[_type == "faq" && naHome == true] | order(ordem asc)[0...5]{    _id, pergunta, resposta,    "respostaTexto": pt::text(resposta)  }
export type FAQ_HOME_RESULT = Array<{
  _id: string;
  pergunta: string | null;
  resposta: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  respostaTexto: string;
}>;

// Source: src/sanity/queries.ts
// Variable: MATERIAL_PRINCIPAL
// Query: *[_type == "material" && ativo == true] | order(_createdAt asc)[0]{    titulo, "slug": slug.current, promessa, capa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}  }
export type MATERIAL_PRINCIPAL_RESULT = {
  titulo: string | null;
  slug: string | null;
  promessa: string | null;
  capa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: MATERIAL_POR_SLUG
// Query: *[_type == "material" && slug.current == $slug && ativo == true][0]{    _id, titulo, "slug": slug.current, promessa, topicos,    capa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    "arquivoUrl": arquivo.asset->url,    seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }}  }
export type MATERIAL_POR_SLUG_RESULT = {
  _id: string;
  titulo: string | null;
  slug: string | null;
  promessa: string | null;
  topicos: Array<string> | null;
  capa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  arquivoUrl: string | null;
  seo: {
    titulo: string | null;
    descricao: string | null;
    naoIndexar: boolean | null;
    imagem: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      lqip: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: POSTS_HOME
// Query: *[_type == "post" && categoria == "preparacao" && publicadoEm <= now()]  | order(publicadoEm desc)[0...3]{    _id, titulo, "slug": slug.current, resumo, categoria, publicadoEm,    capa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}  }
export type POSTS_HOME_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  resumo: string | null;
  categoria: "espiritualidade" | "preparacao" | "relatos" | "roteiros" | null;
  publicadoEm: string | null;
  capa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: POSTS
// Query: *[_type == "post" && publicadoEm <= now()]  | order(publicadoEm desc)[$inicio...$fim]{    _id, titulo, "slug": slug.current, resumo, categoria, publicadoEm,    capa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}  }
export type POSTS_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  resumo: string | null;
  categoria: "espiritualidade" | "preparacao" | "relatos" | "roteiros" | null;
  publicadoEm: string | null;
  capa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: POST_POR_SLUG
// Query: *[_type == "post" && slug.current == $slug][0]{    ...,    "slug": slug.current,    capa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    corpo[]{      ...,      _type == "imagemComAlt" => {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},      markDefs[]{ ..., _type == "link" => { href } }    },    saidasRelacionadas[]-> {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }},    seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }},    "relacionados": *[_type == "post" && categoria == ^.categoria                      && _id != ^._id] | order(publicadoEm desc)[0...3]{      _id, titulo, "slug": slug.current, resumo, capa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}    },    "tempoLeitura": round(length(pt::text(corpo)) / 5 / 200)  }
export type POST_POR_SLUG_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug: string | null;
  categoria?: "espiritualidade" | "preparacao" | "relatos" | "roteiros";
  resumo?: string;
  capa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  publicadoEm?: string;
  corpo: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          href: string | null;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        texto?: string;
        _type: "destaque";
        _key: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "imagemComAlt";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | "";
        legenda?: string;
        lqip: string | null;
        dimensoes: SanityImageDimensions | null;
        markDefs: null;
      }
  > | null;
  saidasRelacionadas: Array<{
    _id: string;
    titulo: string | null;
    slug: string | null;
    dataInicio: string | null;
    dataFim: string | null;
    cidadeSaida: string | null;
    resumo: string | null;
    distanciaKm: number | null;
    nivel: "exigente" | "leve" | "moderado" | null;
    vagasTotal: number | null;
    vagasDisponiveis: number | null;
    valor: string | null;
    destaque: boolean | null;
    imagemCapa: {
      _type: "imagemComAlt";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      legenda?: string;
      lqip: string | null;
      dimensoes: SanityImageDimensions | null;
    } | null;
    ramal: {
      nome: string | null;
      slug: string | null;
      km: number | null;
    } | null;
  }> | null;
  seo: {
    titulo: string | null;
    descricao: string | null;
    naoIndexar: boolean | null;
    imagem: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      lqip: string | null;
    } | null;
  } | null;
  relacionados: Array<{
    _id: string;
    titulo: string | null;
    slug: string | null;
    resumo: string | null;
    capa: {
      _type: "imagemComAlt";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      legenda?: string;
      lqip: string | null;
      dimensoes: SanityImageDimensions | null;
    } | null;
  }>;
  tempoLeitura: number;
} | null;

// Source: src/sanity/queries.ts
// Variable: SLUGS_POST
// Query: *[_type == "post" && defined(slug.current)][]{ "slug": slug.current }
export type SLUGS_POST_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: POSTS_POR_CATEGORIA
// Query: *[_type == "post" && categoria == $categoria && publicadoEm <= now()]  | order(publicadoEm desc){    _id, titulo, "slug": slug.current, resumo, categoria, publicadoEm,    capa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}  }
export type POSTS_POR_CATEGORIA_RESULT = Array<{
  _id: string;
  titulo: string | null;
  slug: string | null;
  resumo: string | null;
  categoria: "espiritualidade" | "preparacao" | "relatos" | "roteiros" | null;
  publicadoEm: string | null;
  capa: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: DEPOIMENTOS
// Query: *[_type == "depoimento" && publicado == true] | order(_createdAt desc){    _id, nome, cidade, texto, videoUrl,    foto {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    saida->{ titulo, "slug": slug.current, dataInicio, ramal->{ nome } }  }
export type DEPOIMENTOS_RESULT = Array<{
  _id: string;
  nome: string | null;
  cidade: string | null;
  texto: string | null;
  videoUrl: string | null;
  foto: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  saida: {
    titulo: string | null;
    slug: string | null;
    dataInicio: string | null;
    ramal: {
      nome: string | null;
    } | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FAQ_COMPLETA
// Query: *[_type == "faq"] | order(ordem asc){    _id, pergunta, resposta, categoria,    "respostaTexto": pt::text(resposta)  }
export type FAQ_COMPLETA_RESULT = Array<{
  _id: string;
  pergunta: string | null;
  resposta: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  categoria:
    "caminho" | "decisao" | "equipamento" | "fisico" | "valores" | null;
  respostaTexto: string;
}>;

// Source: src/sanity/queries.ts
// Variable: RAMAIS
// Query: *[_type == "ramal"] | order(km asc){    _id, nome, "slug": slug.current, cidadeInicio, km,    diasSugeridos, dificuldade, imagem {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions}  }
export type RAMAIS_RESULT = Array<{
  _id: string;
  nome: string | null;
  slug: string | null;
  cidadeInicio: string | null;
  km: number | null;
  diasSugeridos: number | null;
  dificuldade: "exigente" | "leve" | "moderado" | null;
  imagem: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: RAMAL_POR_SLUG
// Query: *[_type == "ramal" && slug.current == $slug][0]{    _id, nome, "slug": slug.current, cidadeInicio, km,    diasSugeridos, dificuldade,    descricao[]{ ..., _type == "imagemComAlt" => {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions} },    imagem {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},    seo{  titulo, descricao, naoIndexar,  imagem { ..., "lqip": asset->metadata.lqip }},    "saidas": *[_type == "saida" && references(^._id) && dataFim >= now()]      | order(dataInicio asc) {  _id,  titulo,  "slug": slug.current,  dataInicio,  dataFim,  cidadeSaida,  resumo,  distanciaKm,  nivel,  vagasTotal,  vagasDisponiveis,  valor,  destaque,  imagemCapa {  ...,  "alt": coalesce(alt, ""),  "lqip": asset->metadata.lqip,  "dimensoes": asset->metadata.dimensions},  ramal->{ nome, "slug": slug.current, km }}  }
export type RAMAL_POR_SLUG_RESULT = {
  _id: string;
  nome: string | null;
  slug: string | null;
  cidadeInicio: string | null;
  km: number | null;
  diasSugeridos: number | null;
  dificuldade: "exigente" | "leve" | "moderado" | null;
  descricao: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  imagem: {
    _type: "imagemComAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    legenda?: string;
    lqip: string | null;
    dimensoes: SanityImageDimensions | null;
  } | null;
  seo: {
    titulo: string | null;
    descricao: string | null;
    naoIndexar: boolean | null;
    imagem: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      lqip: string | null;
    } | null;
  } | null;
  saidas: Array<{
    _id: string;
    titulo: string | null;
    slug: string | null;
    dataInicio: string | null;
    dataFim: string | null;
    cidadeSaida: string | null;
    resumo: string | null;
    distanciaKm: number | null;
    nivel: "exigente" | "leve" | "moderado" | null;
    vagasTotal: number | null;
    vagasDisponiveis: number | null;
    valor: string | null;
    destaque: boolean | null;
    imagemCapa: {
      _type: "imagemComAlt";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      legenda?: string;
      lqip: string | null;
      dimensoes: SanityImageDimensions | null;
    } | null;
    ramal: {
      nome: string | null;
      slug: string | null;
      km: number | null;
    } | null;
  }>;
} | null;

// Source: src/sanity/queries.ts
// Variable: SLUGS_RAMAL
// Query: *[_type == "ramal" && defined(slug.current)][]{ "slug": slug.current }
export type SLUGS_RAMAL_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SITEMAP
// Query: {  "saidas": *[_type == "saida" && defined(slug.current)]{    "slug": slug.current, _updatedAt },  "posts": *[_type == "post" && defined(slug.current) && publicadoEm <= now()]{    "slug": slug.current, _updatedAt },  "ramais": *[_type == "ramal" && defined(slug.current)]{    "slug": slug.current, _updatedAt },  "materiais": *[_type == "material" && ativo == true && defined(slug.current)]{    "slug": slug.current, _updatedAt }}
export type SITEMAP_RESULT = {
  saidas: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  ramais: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  materiais: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}': IMAGEM_RESULT;
    'seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n}': SEO_RESULT;
    '{\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}': CARTAO_SAIDA_RESULT;
    '\n  *[_type == "saida" && dataFim >= now()]\n  | order(dataInicio asc) {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}\n': PROXIMAS_SAIDAS_RESULT;
    '\n  *[_type == "saida" && dataFim >= now()]\n  | order(dataInicio asc)[0...3]{\n    titulo, "slug": slug.current, dataInicio\n  }\n': RODAPE_SAIDAS_RESULT;
    '\n  *[_type == "saida" && dataFim >= now()]\n  | order(destaque desc, dataInicio asc)[0...$limite] {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}\n': SAIDAS_HOME_RESULT;
    '\n  *[_type == "saida" && dataFim < now()]\n  | order(dataInicio desc) {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}\n': SAIDAS_REALIZADAS_RESULT;
    '\n  *[_type == "saida" && slug.current == $slug][0]{\n    ...,\n    "slug": slug.current,\n    imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    galeria[] {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    ramal->{ nome, "slug": slug.current, km, dificuldade, cidadeInicio },\n    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },\n    incluso,\n    naoIncluso,\n    seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n},\n    "depoimentos": *[_type == "depoimento" && publicado == true\n                     && references(^._id)] | order(_createdAt desc){\n      _id, nome, cidade, texto, videoUrl, foto {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n    },\n    "perguntas": *[_type == "faq" && categoria in ["decisao", "valores"]]\n                 | order(ordem asc)[0...6]{ _id, pergunta, resposta }\n  }\n': SAIDA_POR_SLUG_RESULT;
    '\n  *[_type == "saida" && defined(slug.current)][]{ "slug": slug.current }\n': SLUGS_SAIDA_RESULT;
    '\n  *[_type == "saida" && slugGrupo.current == $slug][0]{\n    titulo, dataInicio, dataFim, cidadeSaida, distanciaKm,\n    roteiro[]{ dia, trecho, km, altimetria, pousada, descricao },\n    orientacoesGrupo,\n    incluso, naoIncluso,\n    ramal->{ nome, km }\n  }\n': GRUPO_POR_SLUG_RESULT;
    '\n  *[_type == "configuracao"][0]{\n    whatsapp, email, instagram,\n    heroTitulo, heroSubtitulo, heroCitacao,\n    heroImagem {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    peregrinosGuiados, saidasRealizadas, anoInicio\n  }\n': CONFIGURACAO_RESULT;
    '\n  *[_type == "quemSou"][0]{\n    titulo, credenciais,\n    foto {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    historia[]{ ..., _type == "imagemComAlt" => {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n} },\n    seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n}\n  }\n': QUEM_SOU_RESULT;
    '\n  *[_type == "depoimento" && publicado == true]\n  | order(destaque desc, _createdAt desc)[0...8]{\n    _id, nome, cidade, texto,\n    foto {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    saida->{ dataInicio, ramal->{ nome } }\n  }\n': DEPOIMENTOS_HOME_RESULT;
    '\n  *[_type == "faq" && naHome == true] | order(ordem asc)[0...5]{\n    _id, pergunta, resposta,\n    "respostaTexto": pt::text(resposta)\n  }\n': FAQ_HOME_RESULT;
    '\n  *[_type == "material" && ativo == true] | order(_createdAt asc)[0]{\n    titulo, "slug": slug.current, promessa, capa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n  }\n': MATERIAL_PRINCIPAL_RESULT;
    '\n  *[_type == "material" && slug.current == $slug && ativo == true][0]{\n    _id, titulo, "slug": slug.current, promessa, topicos,\n    capa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    "arquivoUrl": arquivo.asset->url,\n    seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n}\n  }\n': MATERIAL_POR_SLUG_RESULT;
    '\n  *[_type == "post" && categoria == "preparacao" && publicadoEm <= now()]\n  | order(publicadoEm desc)[0...3]{\n    _id, titulo, "slug": slug.current, resumo, categoria, publicadoEm,\n    capa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n  }\n': POSTS_HOME_RESULT;
    '\n  *[_type == "post" && publicadoEm <= now()]\n  | order(publicadoEm desc)[$inicio...$fim]{\n    _id, titulo, "slug": slug.current, resumo, categoria, publicadoEm,\n    capa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n  }\n': POSTS_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    ...,\n    "slug": slug.current,\n    capa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    corpo[]{\n      ...,\n      _type == "imagemComAlt" => {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n      markDefs[]{ ..., _type == "link" => { href } }\n    },\n    saidasRelacionadas[]-> {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n},\n    seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n},\n    "relacionados": *[_type == "post" && categoria == ^.categoria\n                      && _id != ^._id] | order(publicadoEm desc)[0...3]{\n      _id, titulo, "slug": slug.current, resumo, capa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n    },\n    "tempoLeitura": round(length(pt::text(corpo)) / 5 / 200)\n  }\n': POST_POR_SLUG_RESULT;
    '\n  *[_type == "post" && defined(slug.current)][]{ "slug": slug.current }\n': SLUGS_POST_RESULT;
    '\n  *[_type == "post" && categoria == $categoria && publicadoEm <= now()]\n  | order(publicadoEm desc){\n    _id, titulo, "slug": slug.current, resumo, categoria, publicadoEm,\n    capa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n  }\n': POSTS_POR_CATEGORIA_RESULT;
    '\n  *[_type == "depoimento" && publicado == true] | order(_createdAt desc){\n    _id, nome, cidade, texto, videoUrl,\n    foto {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    saida->{ titulo, "slug": slug.current, dataInicio, ramal->{ nome } }\n  }\n': DEPOIMENTOS_RESULT;
    '\n  *[_type == "faq"] | order(ordem asc){\n    _id, pergunta, resposta, categoria,\n    "respostaTexto": pt::text(resposta)\n  }\n': FAQ_COMPLETA_RESULT;
    '\n  *[_type == "ramal"] | order(km asc){\n    _id, nome, "slug": slug.current, cidadeInicio, km,\n    diasSugeridos, dificuldade, imagem {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n}\n  }\n': RAMAIS_RESULT;
    '\n  *[_type == "ramal" && slug.current == $slug][0]{\n    _id, nome, "slug": slug.current, cidadeInicio, km,\n    diasSugeridos, dificuldade,\n    descricao[]{ ..., _type == "imagemComAlt" => {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n} },\n    imagem {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n    seo{\n  titulo, descricao, naoIndexar,\n  imagem { ..., "lqip": asset->metadata.lqip }\n},\n    "saidas": *[_type == "saida" && references(^._id) && dataFim >= now()]\n      | order(dataInicio asc) {\n  _id,\n  titulo,\n  "slug": slug.current,\n  dataInicio,\n  dataFim,\n  cidadeSaida,\n  resumo,\n  distanciaKm,\n  nivel,\n  vagasTotal,\n  vagasDisponiveis,\n  valor,\n  destaque,\n  imagemCapa {\n  ...,\n  "alt": coalesce(alt, ""),\n  "lqip": asset->metadata.lqip,\n  "dimensoes": asset->metadata.dimensions\n},\n  ramal->{ nome, "slug": slug.current, km }\n}\n  }\n': RAMAL_POR_SLUG_RESULT;
    '\n  *[_type == "ramal" && defined(slug.current)][]{ "slug": slug.current }\n': SLUGS_RAMAL_RESULT;
    '{\n  "saidas": *[_type == "saida" && defined(slug.current)]{\n    "slug": slug.current, _updatedAt },\n  "posts": *[_type == "post" && defined(slug.current) && publicadoEm <= now()]{\n    "slug": slug.current, _updatedAt },\n  "ramais": *[_type == "ramal" && defined(slug.current)]{\n    "slug": slug.current, _updatedAt },\n  "materiais": *[_type == "material" && ativo == true && defined(slug.current)]{\n    "slug": slug.current, _updatedAt }\n}': SITEMAP_RESULT;
  }
}
